### ISSUE TITLE
Create plugin starting structure

### ISSUE THREAD

**Issue by AleksandarPredic** [wceu/contributor-orientation-tool#1]
Create basic plugin structure, autoloader included.

**Comment by zzap** [comment]
I have few suggestions:

1. .editorconfig
Considering that we're planning for this plugin to go to wordpress.org and wordcamp.org, let's use their standards: `indent_style` should be tab.

2. Namespace
While we are still at the beginning, can we change the namespace? `WCEUCDTool` is too narrow, suggesting this is the tool only for WordCamp Europe Contributor Day. Let's do something with `WordPress Contributor Orientation Tool` to cover both wordpress.org and worcamp.org. That would be `WPCOT` which follows the `WPORG` convention for .org projects.

**Comment by AleksandarPredic** [comment]
@zzap you are always one step ahead :+1:  I wanted to ask a review from you, but I used the force to give you the message and i worked. I knew you are a jedi :)

Now seriously:
1. .editorconfig
 I'll change this to tab

2. Namespace
New namespace will be WCOTool. Ok?

I still have some work to do here and when I'm done I'll add info to readme file and some instruction for workflow as we spoke.

**Comment by zzap** [comment]
`WPCOTool` please :smiley:
