### ISSUE TITLE
Make Accessibility more visible and add it also for Designers

### ISSUE THREAD

**Issue by 00travelgirl00** [wceu/contributor-orientation-tool#43]
If I select every role (Developer, Designer, ...) I see these options: 

<img width="872" alt="Bildschirmfoto 2019-06-03 um 12 04 22" src="https://user-images.githubusercontent.com/21318377/58794159-db0d2980-85f7-11e9-8de5-254174ccefda.png">

I would love to select "Accessibility" here, cause I'm super passionate about it. But I can't see it. 

Only if I select 
- "I'm a Developer" 
- and I am Passionate about "Web development, backend development etc."
-  and I have experience in "Implementing accessibility standards" 

I get the Team "Accessibility"- Which only attract people who already now stuff about it. But it would be great also to have contributers on the A11y-Table who are new to Accessibility but are intresting in learning it (in fact, thats typical for the a11y table on a contributor day). 

It would be also great to not only make it possible for developers, but also for designers and other skills, as Accessibility needs a wide range of skills. 

For example, I am a Designer and still contribute to Accessibility, so I would suggest to make "Accessibility" a selected item on the screen "what are you passionate about".

**Comment by AleksandarPredic** [comment]
Hi @00travelgirl00 ,

Thanks for this info. 

The logic behind the scenes is that whatever option you choose in the first section you will for sure get "Web development, backend development etc." option in second section. I suggest that we only change the name of the option to "Web development, backend development, implementing accessibility, etc.". This will give more exposure for the Accessibility, so you can select this option and than you can select appropriate option in next section.

I don't support the idea to make "Accessibility" a selected item on the screen "what are you passionate about" as after that we have to allow other teams to have it's own options here. For the current working solution I feel that it covers almost all the needs of such tool as this one is.

Third section has headline "Are these areas you have experience with or are eager to try?" so anyone is welcome to check any option even if there is no experience for that area as we have "eager to try" in headline as call to action. 

So by changing the name of the option to "Web development, backend development, implementing accessibility, etc." we allow all types of users to have this option in section 2 and to select "Accessibility" in section 3. I suggest that we implement this solution.

**Comment by 00travelgirl00** [comment]
I agree with the solution for experience, but not so much by including Accessibility only into "Web Development", cause that gives the impression, that Accessibility is strongly connected to Development, but the Accessibility Team needs also Designers, Content Creators and so on. 

Also I not really see the issue to include it into the screen "What are you passionate about" as also the Teams Polyglot, Support, Documentation, Marketing, Design and Mobile are represented there.

**Comment by AleksandarPredic** [comment]
Ok, now I see your point. I have to agree with you :)

Than we go with the solution to make "Accessibility" a selected item on the screen "what are you passionate about" and no changes in section 3 for experience.

Can you please suggest correct text for this option? It should be different from the section 3 "Implementing accessibility standards" and still ask user if he is passionate about it. 

Or just call it "Accessibility"?

**Comment by 00travelgirl00** [comment]
Cool, tank you :-) <3 

I think Accessibility is a good term, cause its not always about "implementic". Sometimes is just to point out the A11y-issues and explaining it to core/meta and other teams, so devs can fix it.

**Comment by AleksandarPredic** [comment]
Ok, so final issue task is:

- Make "Accessibility" a selected item on the screen "what are you passionate about".
- Option name is "Accessibility"

Thanks @00travelgirl00 for helping use make this tool better :+1:

**Comment by 00travelgirl00** [comment]
This makes me soooo happy. Thank you so much!

**Comment by AleksandarPredic** [comment]
We can apply this issue while working on issue #47
